version: '3.8'

services:
  whiteboard-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - whiteboard-network

networks:
  whiteboard-network:
    driver: bridge 