version: '3.8'

services:
  whiteboard-app:
    build: .
    ports:
      - "5000:5000"
      - "50051:50051"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - whiteboard-network

  redis:
    image: "redis:alpine"
    networks:
      - whiteboard-network
    restart: unless-stopped

networks:
  whiteboard-network:
    driver: bridge 