# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_shapes_pb2 as grpc__shapes__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_shapes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShapeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateShape = channel.unary_unary(
                '/ShapeService/CreateShape',
                request_serializer=grpc__shapes__pb2.Shape.SerializeToString,
                response_deserializer=grpc__shapes__pb2.ShapeResponse.FromString,
                _registered_method=True)
        self.UpdateShape = channel.unary_unary(
                '/ShapeService/UpdateShape',
                request_serializer=grpc__shapes__pb2.Shape.SerializeToString,
                response_deserializer=grpc__shapes__pb2.ShapeResponse.FromString,
                _registered_method=True)
        self.DeleteShape = channel.unary_unary(
                '/ShapeService/DeleteShape',
                request_serializer=grpc__shapes__pb2.ShapeId.SerializeToString,
                response_deserializer=grpc__shapes__pb2.ShapeResponse.FromString,
                _registered_method=True)


class ShapeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateShape(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateShape(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteShape(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShapeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateShape': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateShape,
                    request_deserializer=grpc__shapes__pb2.Shape.FromString,
                    response_serializer=grpc__shapes__pb2.ShapeResponse.SerializeToString,
            ),
            'UpdateShape': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateShape,
                    request_deserializer=grpc__shapes__pb2.Shape.FromString,
                    response_serializer=grpc__shapes__pb2.ShapeResponse.SerializeToString,
            ),
            'DeleteShape': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteShape,
                    request_deserializer=grpc__shapes__pb2.ShapeId.FromString,
                    response_serializer=grpc__shapes__pb2.ShapeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ShapeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ShapeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShapeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateShape(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ShapeService/CreateShape',
            grpc__shapes__pb2.Shape.SerializeToString,
            grpc__shapes__pb2.ShapeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateShape(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ShapeService/UpdateShape',
            grpc__shapes__pb2.Shape.SerializeToString,
            grpc__shapes__pb2.ShapeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteShape(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ShapeService/DeleteShape',
            grpc__shapes__pb2.ShapeId.SerializeToString,
            grpc__shapes__pb2.ShapeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
