# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_shapes.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'grpc_shapes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpc_shapes.proto\"\xab\x01\n\x05Shape\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\t\n\x01x\x18\x03 \x01(\x01\x12\t\n\x01y\x18\x04 \x01(\x01\x12\r\n\x05width\x18\x05 \x01(\x01\x12\x0e\n\x06height\x18\x06 \x01(\x01\x12\r\n\x05\x63olor\x18\x07 \x01(\t\x12\x0c\n\x04text\x18\x08 \x01(\t\x12\x11\n\tfont_size\x18\t \x01(\x05\x12\x0f\n\x07version\x18\n \x01(\x05\x12\x12\n\nsession_id\x18\x0b \x01(\t\")\n\x07ShapeId\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"H\n\rShapeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\x05shape\x18\x03 \x01(\x0b\x32\x06.Shape2\x85\x01\n\x0cShapeService\x12%\n\x0b\x43reateShape\x12\x06.Shape\x1a\x0e.ShapeResponse\x12%\n\x0bUpdateShape\x12\x06.Shape\x1a\x0e.ShapeResponse\x12\'\n\x0b\x44\x65leteShape\x12\x08.ShapeId\x1a\x0e.ShapeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_shapes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHAPE']._serialized_start=22
  _globals['_SHAPE']._serialized_end=193
  _globals['_SHAPEID']._serialized_start=195
  _globals['_SHAPEID']._serialized_end=236
  _globals['_SHAPERESPONSE']._serialized_start=238
  _globals['_SHAPERESPONSE']._serialized_end=310
  _globals['_SHAPESERVICE']._serialized_start=313
  _globals['_SHAPESERVICE']._serialized_end=446
# @@protoc_insertion_point(module_scope)
