services:
  # 1. Serviço Redis
  - type: redis
    name: redis
    plan: free
    ipAllowList:  # Regra para permitir conexões
      - cidr: 0.0.0.0/0
        description: "Allow all"

  # 2. Aplicação Web (Flask/gRPC)
  - type: web
    name: whiteboard-app
    plan: free
    runtime: docker
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: FLASK_ENV
        value: production
      # O Render injeta a URL do serviço Redis automaticamente
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      # As variáveis a seguir devem ser adicionadas na aba "Environment" do dashboard do Render
      # SUPABASE_URL, SUPABASE_API_KEY, FLASK_SECRET_KEY