services:
  # 1. Serviço Redis
  - type: redis
    name: redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: "Allow all connections"

  # 2. Aplicação Web (Flask/gRPC)
  - type: web
    name: whiteboard-app
    plan: free
    runtime: docker
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: FLASK_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      # Lembre-se de adicionar as variáveis SUPABASE_URL, SUPABASE_API_KEY, 
      # e FLASK_SECRET_KEY no dashboard da Render na aba "Environment".