services:
  # 1. Serviço Redis
  # Render irá criar e gerenciar uma instância Redis gratuita para nós.
  - type: redis
    name: redis
    plan: free # Plano gratuito do Render

  # 2. Aplicação Web (Flask/gRPC)
  # Render irá construir a imagem a partir do nosso Dockerfile e executar.
  - type: web
    name: whiteboard-app
    plan: free # Plano gratuito do Render (pode hibernar após inatividade)
    runtime: docker
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED # Garante que os logs do Python apareçam em tempo real
        value: 1
      - key: FLASK_ENV
        value: production
      # O Render injeta a URL do serviço Redis automaticamente
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      # As chaves a seguir devem ser adicionadas como "Secret Files" no dashboard do Render
      - key: SUPABASE_URL
        fromSecret: true
      - key: SUPABASE_API_KEY
        fromSecret: true
      - key: FLASK_SECRET_KEY
        fromSecret: true 